[package]
name = "ttk4145_elevator_server"
version = "0.1.0"
authors = ["Kjetil Kjeka"]

[[bin]]
name = "elevator_server"

[dependencies]
libc = "0.2.34"

[dev-dependencies]
lazy_static = "1.0"
rand = "0.4"